In [4]:
import numpy as np

numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print("numpy array variable:\n{}".format(numpy_array))

numpy array variable:
[[1 2 3]
 [4 5 6]]


In [11]:
#use eye to create a diagonal matrix of ones
eye = np.eye(4)
print("NumPy array:\n", eye)

NumPy array:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#A sparse matrix has mostly zeroes
#Convert the NumPy array to a SciPy sparse matrix in CSR format
#Only the nonzero entries are stored, this saves memory
from scipy import sparse
sparse_matrix = sparse.csr_matrix(eye)
#column indices for row i are stored in indices[indptr[i]:indptr[i+1]] 
#and their corresponding values are stored in data[indptr[i]:indptr[i+1]]. 

In [15]:
print('sparse_matrix:\n',sparse_matrix)

sparse_matrix:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [8]:
import sys
print("Python version:", sys.version)

import pandas as pd
print("pandas version:", pd.__version__)

import matplotlib
print("matplotlib version:", matplotlib.__version__)

import numpy as np
print("NumPy version:", np.__version__)

import scipy as sp
print("SciPy version:", sp.__version__)

import IPython
print("IPython version:", IPython.__version__)

import sklearn
print("scikit-learn version:", sklearn.__version__)

Python version: 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
pandas version: 2.0.3
matplotlib version: 3.7.2
NumPy version: 1.24.3
SciPy version: 1.11.1
IPython version: 8.15.0
scikit-learn version: 1.3.0
